//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 03/09/2015 22:18:26
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace MetroWPDemo.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Pin"
        /// </summary>
        public static string AppBarButtonPin
        {
            get
            {
                return resourceLoader.GetString("AppBarButtonPin");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "MetroWPDemo"
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return resourceLoader.GetString("ApplicationName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Camera"
        /// </summary>
        public static string ButtonCamera
        {
            get
            {
                return resourceLoader.GetString("ButtonCamera");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sensor"
        /// </summary>
        public static string ButtonSensor
        {
            get
            {
                return resourceLoader.GetString("ButtonSensor");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Sensor"
        /// </summary>
        public static string ButtonSensorContent
        {
            get
            {
                return resourceLoader.GetString("ButtonSensorContent");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Winrt XAML"
        /// </summary>
        public static string ButtonWinrtXaml
        {
            get
            {
                return resourceLoader.GetString("ButtonWinrtXaml");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "DebugCode"
        /// </summary>
        public static string DebugContent
        {
            get
            {
                return resourceLoader.GetString("DebugContent");
            }
        }
    }
}
